# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d0360291bfb0b971727207e0120d22c80f3439b105f4525ebd1d74b97dc48c4ed0eb73f91c121db530b39b06e31ad1d311d12660596ca708419bbb6d24ed3f73

test:
  secret_key_base: 2b0a25cac5b26fc34e0a9e3f37ea6d90e73a9264891f03254c80941a9e507c87abc0205271d8d1d2538cd16452a6fc41f31b03964fff2d2e9599ab08fd285bd8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
